name       : ant-nebula-gtk-theme
version    : 1.3.0
release    : 3
source     :
    - https://github.com/EliverLara/Ant-Nebula/archive/v1.3.0.tar.gz : 5b197cf816a576dd090e4faad9e54458d95955fbbb6d2823cca0e3437c18f507
license    : GPL-3.0-or-later
component  : desktop.themes
summary    : Nebula variant of the Ant Theme
description: |
    Nebula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Nebula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Nebula/index.theme
