name       : ant-nebula-gtk-theme
version    : 1.1.0
release    : 1
source     :
    - https://github.com/EliverLara/Ant-Nebula/archive/v1.1.0.tar.gz : 3e1e8485fdb4969f98aed0607bbaee70c3ac92f5e3ec093d12e95059408424a1
license    : GPL-3.0
component  : desktop.themes
summary    : Nebula variant of the Ant Theme
description: |
    Nebula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Nebula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Nebula/index.theme
