name       : ant-nebula-gtk-theme
version    : 1.2.0
release    : 2
source     :
    - https://github.com/EliverLara/Ant-Nebula/archive/v1.2.0.tar.gz : db08a6ceceacf12e50fcfc9bc8aa5ff54c20c80e28fca8559f0a87133721c599
license    : GPL-3.0
component  : desktop.themes
summary    : Nebula variant of the Ant Theme
description: |
    Nebula variant of the Ant Theme
rundeps    :
    - gtk2-engine-murrine
install    : |
    for dir in assets gnome-shell gtk-2.0 gtk-3.0 gtk-3.20 metacity-1; do
        for file in $(find ${dir} -type f); do
            install -Dm 00644 "$file" $installdir/usr/share/themes/Ant-Nebula/"$file"
        done
    done

    install -Dm 00644 index.theme $installdir/usr/share/themes/Ant-Nebula/index.theme
